# Generated by Django 5.1.7 on 2025-05-22 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('localizacao', models.CharField(max_length=255)),
                ('horario_atendimento', models.CharField(blank=True, max_length=100, null=True)),
                ('contato', models.CharField(blank=True, max_length=150, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiaOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('concluido', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('endereco', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItemEntregavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('tipo', models.CharField(choices=[('gestao', 'Gestão Condominial'), ('contabilidade', 'Contabilidade')], default='gestao', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiaContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('concluido', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresacontabil')),
            ],
            options={
                'unique_together': {('data', 'empresa')},
            },
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('coleta', 'Coleta'), ('retirada', 'Retirada'), ('coleta e retirada', 'Coleta e Retirada')], max_length=20)),
                ('responsavel', models.CharField(max_length=100)),
                ('destinatario', models.CharField(blank=True, max_length=100, null=True)),
                ('horario_coleta', models.CharField(blank=True, max_length=20, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='comprovantes/')),
                ('protocolo', models.BooleanField(default=False)),
                ('malote', models.BooleanField(default=False)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.condominio')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacoes', to='core.diaoperacao')),
                ('itens_entregues', models.ManyToManyField(blank=True, to='core.itementregavel')),
            ],
        ),
        migrations.CreateModel(
            name='OperacaoContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('coleta', 'Coleta'), ('retirada', 'Retirada'), ('coleta e retirada', 'Coleta e Retirada')], max_length=20)),
                ('solicitante', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=100)),
                ('protocolo', models.BooleanField(default=False)),
                ('malote', models.BooleanField(default=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nome', models.CharField(max_length=100)),
                ('diaContabil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.diacontabil')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresacontabil')),
            ],
        ),
    ]
