# Generated by Django 5.1.7 on 2025-05-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diacontabil',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
    ]
