# Generated by Django 5.1.7 on 2025-05-21 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operacaocontabil',
            old_name='busca',
            new_name='malote',
        ),
        migrations.RenameField(
            model_name='operacaocontabil',
            old_name='entrega',
            new_name='protocolo',
        ),
        migrations.RemoveField(
            model_name='operacaocontabil',
            name='dia',
        ),
        migrations.AddField(
            model_name='diacontabil',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operacaocontabil',
            name='diaContabil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.diacontabil'),
        ),
        migrations.AddField(
            model_name='operacaocontabil',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.empresacontabil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operacaocontabil',
            name='nome',
            field=models.CharField(default='Teste', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operacaocontabil',
            name='tipo',
            field=models.CharField(choices=[('coleta', 'Coleta'), ('retirada', 'Retirada'), ('coleta e retirada', 'Coleta e Retirada')], default='aleatorio', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diacontabil',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresacontabil'),
        ),
    ]
