# Generated by Django 5.2.1 on 2025-05-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_condominio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominio',
            name='contato',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='horario_atendimento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
