# Generated by Django 5.1.7 on 2025-05-21 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_diacontabil_concluido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operacaocontabil',
            old_name='dia',
            new_name='diaContabil',
        ),
        migrations.AddField(
            model_name='operacaocontabil',
            name='tipo',
            field=models.CharField(choices=[('coleta', 'Coleta'), ('retirada', 'Retirada'), ('coleta e retirada', 'Coleta e Retirada')], default='none', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diacontabil',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresacontabil'),
        ),
    ]
