# Generated by Django 5.1.7 on 2025-05-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_diacontabil_criado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacaocontabil',
            name='tipo',
            field=models.CharField(choices=[('entrega', 'Entrega'), ('retirada', 'Retirada'), ('entrega e retirada', 'Entrega e Retirada')], max_length=20),
        ),
    ]
