# Generated by Django 5.1.7 on 2025-05-21 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_dia_operacaocontabil_diacontabil_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operacaocontabil',
            old_name='busca',
            new_name='malote',
        ),
        migrations.RenameField(
            model_name='operacaocontabil',
            old_name='entrega',
            new_name='protocolo',
        ),
    ]
