# Generated by Django 5.1.7 on 2025-05-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_operacaocontabil_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='diacontabil',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
