# Generated by Django 5.2.1 on 2025-05-19 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_condominio_contato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('coleta', 'Coleta'), ('retirada', 'Retirada'), ('coleta e retirada', 'Coleta e Retirada')], max_length=20)),
                ('responsavel', models.CharField(max_length=100)),
                ('destinatario', models.CharField(blank=True, max_length=100, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='comprovantes/')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.condominio')),
            ],
        ),
    ]
