# Generated by Django 5.2.1 on 2025-05-19 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_operacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='operacao',
            name='dia',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='operacoes', to='core.diaoperacao'),
            preserve_default=False,
        ),
    ]
