# Generated by Django 5.1.7 on 2025-05-21 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_busca_operacaocontabil_malote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacaocontabil',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.empresacontabil'),
            preserve_default=False,
        ),
    ]
