# Generated by Django 5.1.7 on 2025-05-28 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_operacao_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnderecoCondominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=255)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='core.condominio')),
            ],
        ),
    ]
