# Generated by Django 5.2.1 on 2025-05-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_diaoperacao_operacao_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacao',
            name='data_hora',
        ),
        migrations.AddField(
            model_name='operacao',
            name='horario_coleta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
