# Generated by Django 5.2.1 on 2025-05-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_operacao_data_hora_operacao_horario_coleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao',
            name='malote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operacao',
            name='protocolo',
            field=models.BooleanField(default=False),
        ),
    ]
