# Generated by Django 5.1.7 on 2025-06-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_enderecocondominio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemEntregue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='operacao',
            name='itens_recebidos',
            field=models.ManyToManyField(blank=True, related_name='recebimentos', to='core.itementregavel'),
        ),
    ]
