# Generated by Django 5.1.7 on 2025-06-10 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_itementregue_operacao_itens_recebidos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operacao',
            old_name='itens_recebidos',
            new_name='itens_devolvidos',
        ),
    ]
