# Generated by Django 5.1.7 on 2025-05-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_operacao_malote_operacao_protocolo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemEntregavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='operacao',
            name='itens_entregues',
            field=models.ManyToManyField(blank=True, to='core.itementregavel'),
        ),
    ]
