# Generated by Django 5.1.7 on 2025-05-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_itementregavel_operacao_itens_entregues'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaoperacao',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
    ]
