# Generated by Django 5.1.7 on 2025-05-21 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_empresa_usuario_tipo_usuario_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaoperacao',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
    ]
