# Generated by Django 5.1.7 on 2025-05-21 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_diaoperacao_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='contabilidade_responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_empresa': 'contabilidade'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_empresa',
            field=models.CharField(choices=[('gestao', 'Gestão Condominial'), ('contabilidade', 'Contabilidade')], default='gestao', max_length=20),
        ),
    ]
