# Generated by Django 5.1.7 on 2025-05-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_empresa_contabilidade_responsavel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaoperacao',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='diaoperacao',
            unique_together={('data', 'empresa')},
        ),
    ]
